#!/bin/bash

source "$MIMIRON_INSTALL/config/config.sh"
source "$MIMIRON_INSTALL/config/git.sh"
source "$MIMIRON_INSTALL/config/gpg.sh"
source "$MIMIRON_INSTALL/config/timezones.sh"
source "$MIMIRON_INSTALL/config/fast-shutdown.sh"
source "$MIMIRON_INSTALL/config/increase-sudo-tries.sh"
source "$MIMIRON_INSTALL/config/increase-lockout-limit.sh"
source "$MIMIRON_INSTALL/config/ssh-flakiness.sh"
source "$MIMIRON_INSTALL/config/mimetypes.sh"
source "$MIMIRON_INSTALL/config/mise.sh"
source "$MIMIRON_INSTALL/config/localdb.sh"
source "$MIMIRON_INSTALL/config/gdm.sh"
source "$MIMIRON_INSTALL/config/gnome-extensions.sh"
source "$MIMIRON_INSTALL/config/hardware/all.sh"
